# Generated by Django 5.2.7 on 2025-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
